### PR TITLE
front: harmonize timesstops component name in scenario

### PR DESCRIPTION
**Pull request by Synar**
Turn all occurences of timeStops to timesStops

There were more occurences of timesStops than timeStops hence the change in this sense, but I'm fine with the other way too, as long as we make a single choice.

### CODE REVIEW

**Review by kmer2016 — APPROVED** [review]
LGTM !

**Review by Yohh — APPROVED** [review]
lgtm

**Review by RomainValls — APPROVED** [review]
LGTM 👍

**Comment by SharglutDev** [comment]
Seems like @Yohh 's approval didn't count as a `OSRD-E2E-Tests` (but it still doesn't block the merge) ?

**Comment by Yohh** [comment]
> Seems like @Yohh 's approval didn't count as a `OSRD-E2E-Tests` (but it still doesn't block the merge) ?

I think this is because this PR was opened last week no? or maybe I'm fired...

**Pull request merged**
