### PR TITLE
front: fix flaky test 012 and 006

### PR DESCRIPTION
**Pull request by Maymanaf**
This PR addresses the flakiness in tests 006 and 012.
The Playwright runner is very fast, which sometimes prevents the results from being updated in time. To resolve this, I added timeouts

### CODE REVIEW

**Review by Synar — COMMENTED** [review]
Nice PR! There's a slight redundancy with https://github.com/OpenRailAssociation/osrd/pull/9614/commits/8248abec283ae79b5cbef44b455b8233b5904b82 which adds ```await page.waitForSelector(containerSelector, { state: 'visible' });``` to the top of the scroll container function

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:

**Comment by Maymanaf** [comment]
> Nice PR! There's a slight redundancy with [8248abe](https://github.com/OpenRailAssociation/osrd/commit/8248abec283ae79b5cbef44b455b8233b5904b82) which adds `await page.waitForSelector(containerSelector, { state: 'visible' });` to the top of the scroll container function

I don't see any redundancy in this case, as I didn't modify the scroll function. Additionally, the use of waitForSelector shouldn't cause any issues since it doesn't rely on a fixed timeout.

**Review by Yohh — APPROVED** [review]
lgtm

**Comment by Synar** [comment]
> > Nice PR! There's a slight redundancy with [8248abe](https://github.com/OpenRailAssociation/osrd/commit/8248abec283ae79b5cbef44b455b8233b5904b82) which adds `await page.waitForSelector(containerSelector, { state: 'visible' });` to the top of the scroll container function
> 
> I don't see any redundancy in this case, as I didn't modify the scroll function. Additionally, the use of waitForSelector shouldn't cause any issues since it doesn't rely on a fixed timeout.

Yes, but you are waiting for the table to be visible before calling the scroll function at multiple points, and my change makes the scroll function wait for the component it should scroll to be visible, so we solved the same bug twice. It shouldn't pose any issue though. If the table is visible once, it should be visible twice =p

**Pull request merged**
