### PR TITLE
Update bug_report.yaml

### PR DESCRIPTION
**Pull request by axrolld**
Remove degexsol and set rec as the default env

### CODE REVIEW

**Review by Castavo — APPROVED** [review]
Neat

**Comment by emersion** [comment]
Maybe add "github:" as the commit title prefix to make CI happy?

**Review by flomonster — APPROVED** [review]
LGTM

**Review by bloussou — APPROVED** [review]
🚀

**Comment by emersion** [comment]
This makes GitHub unhappy, fix in https://github.com/OpenRailAssociation/osrd/pull/8626.

**Pull request merged**
