### PR TITLE
front: fix the issue where the 'More details' button stopped working

### LINKED ISSUE #9181: `more details` button doesn't work anymore in the train list
### What happened?

image

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

.

### On which environments the bug occurs?

Dev (SNCF)
Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

8795495

### PR DESCRIPTION
**Pull request by achrafmohye**
Closes #9181

### CODE REVIEW

**Review by woshilapin — COMMENTED** [review]
If this was a regression, maybe we need a test to avoid another regression later?

**Review by theocrsb — APPROVED** [review]
LGTM and tested

**Review by SarahBellaha — APPROVED** [review]
LGTM

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:

**Comment by clarani** [comment]
@woshilapin I think the better way to test this is by an e2e test. The e2e test are planned and developed by @Maymanaf right now, so I think we won't add the test in this PR. But we can do it later, with @Maymanaf :)

**Comment by Maymanaf** [comment]
> @woshilapin I think the better way to test this is by an e2e test. The e2e test are planned and developed by @Maymanaf right now, so I think we won't add the test in this PR. But we can do it later, with @Maymanaf :)

The timetable management tests are planned but not prioritized for now : You can check the order #7706

**Comment by achrafmohye** [comment]
> If this was a regression, maybe we need a test to avoid another regression later?

Don't think it's a regression that needs testing, i guess it was rather an oversight

**Pull request merged**
