### PR TITLE
front: rolling stock editor responsive fixes

### LINKED ISSUE #5573: Responsiveness problems in rolling stock editor
### What happened?

The Davis formula collapses when the screen become too small here.
image

Also in the rolling stock curves editor the 4 blocks collapse in 3-1 and not 2-2 when the screen's too small:

Image

### OSRD version (top right corner `Account` button > `Informations`)

c2b9acd3

### PR DESCRIPTION
**Pull request by Wadjetz**
close #5573

### CODE REVIEW

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:  tested

**Review by SharglutDev — APPROVED** [review]
Lgtm :)

**Comment by axrolld** [comment]
Could this be the occasion to make those components take the entire width of the div ? I don't know if this opinion is shared but that's how i imagined this fix. I find the collapsed view kinda weird because of all the white space left to the right.

If everyone's ok with the current fix just ignore this comment it's not a big deal :)

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Since @thibautsailly 's last comment, I think we need a meeting with @axrolld to have a final decision about the behavior of this section

**Review by SharglutDev — CHANGES_REQUESTED** [review]
It seems like in large screens, the rollingstock selector component's width is still growing

**Review by SharglutDev — APPROVED** [review]
Lgtm good job :)

**Pull request merged**
