### PR TITLE
front: fix modal zindex #5395

### PR DESCRIPTION
**Pull request by sim51**
See issue #5395

Modal should be on top of everything, even on top of the app header

### CODE REVIEW

**Comment by kmer2016** [comment]
It would be more maintainable and organized to declare all z-index values as CSS constants in a central location and then utilize these variables throughout the codebase. perhaps in a separate PR.

**Comment by sim51** [comment]
In the front application, we use the SNCF bootstrap and we include it as CSS (check https://github.com/osrd-project/osrd/blob/dev/front/src/main/app.jsx#L23)
So I was not able to take the zIndex variable for the masthead and make a `+1`.

I'm in favor to centralized all the zIndex, but right now it's not possible ... 
Is it possible to use the SNCF bootstrap by using its sass version instead of the css one ?

**Comment by clarani** [comment]
@Math-R  is refactoring the router right now, I think we can refactor the mast header after that and centralize the z-index later ? If you agree, I can review the PR now

**Review by clarani — APPROVED** [review]
LGTM, tested in local

**Pull request merged**
