### PR TITLE
editoast: add missing signal fields to infra clones

### LINKED ISSUE #5828: Signals not displayed on a duplicated infra
### What happened?

Trying to fix a route issue near Sète train station, i displayed the signals but only the names are being dispayed, not the objects. This only happens on the infra that i duplicated, not the original one.

image

Same bug on the map module.

### What did you expect to happen?

The signals should be displayed, not only the names.

### How can we reproduce it (as minimally and precisely as possible)?

1. Duplicate france_snapping
2. Go to the map or infra editor
3. Display signals layer
### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging degexsol

### OSRD version (top right corner `Account` button > `Informations`)

2019297

### PR DESCRIPTION
**Pull request by shenriotpro**
fixes https://github.com/osrd-project/osrd/issues/5828

### CODE REVIEW

**Review by flomonster — APPROVED** [review]
Good catch. Thanks!

**Review by axrolld — APPROVED** [review]
LGTM !
Should the tests be part of this PR as well ?

**Comment by shenriotpro** [comment]
> LGTM ! Should the tests be part of this PR as well ?

In theory yes, in practice I don't have a great solution for now..

**Review by Tguisnet — APPROVED** [review]
Thanks !

**Pull request merged**
