### PR TITLE
api: editoast: front: use Document system to store rolling_stock images

### LINKED ISSUE #3552: editoast: api: refacto image system to use the document system
# Description
The rolling stock images are stored in their own table for the moment, but they should be moved to the document table. Only the field data will be replaced by a document_id.
We will then use the document functions to create, retrieve and delete a rolling stock image.

# Goal
Store all the documents in the same table.

# Acceptance Criteria
- [ ] the images are stored in the document table
- [ ] when we delete a livery, then all its images and document are removed
- [ ] when we delete a rolling_stock, then all its liveries and their images (and documents) are removed

### PR DESCRIPTION
**Pull request by clarani**
closes #3552

To merge after #3644 and #3642

Change log
- api
  - modify the model of rolling_stock_livery:
    - the image of the livery is now stored in the Document table (so the livery.compound_image_id is a 1to1 FK to Document, nullable)
    - the model CompoundImage is not needed anymore
    - the model RollingStockSeparatedImage is still needed because we store the order of the images (to reorder them when we display them), but its image field has been replaced by a 1to1 FK image_id (linking to Document)
  - update the endpoint to create a livery with the new model
- editoast
  - update the model of RollingStockLivery and implement the trait Delete (from Model)
  - move the rollingStockSeparatedImage to /models (not used for the moment)
  - in RollingStockLiveryMetadata, add the compound_image_id for each livery (useful to retrieve the image with the document endpoint)
  - remove the endpoint GET rolling_stock/{id}/livery/{id} (as we will use the document endpoint now the fetch the image)
  - create fixtures for rolling_stock_livery and document (and update tests)
  - fix imports
- front
  - use the editoast endpoints to get the rolling_stocks with the whole metadata of the liveries (and especially the compound_image_id)
  - create a reusable function to fetch document
  - to display the rolling_stock image, now use the document endpoint

As this PR is already quite big, I will migrate the endpoints to RTK in an other PR

### CODE REVIEW

**Review by clarani — COMMENTED** [review]
Ready for review, I have tested:
- the migration (and its rollback)
- the import of the liveries (with osrd-dags)
- the frontend, the liveries are correctly displayed (and the error messages too)

**Review by flomonster — DISMISSED** [review]
LGTM. I didn't test importing rolling stocks.

**Review by clarani — COMMENTED** [review]
Waiting for front review

**Review by Tguisnet — APPROVED** [review]
LGTM, tested

**Review by Math-R — APPROVED** [review]

**Pull request merged**
