### PR TITLE
front: i18n: rollingstock.json spelling

### PR DESCRIPTION
**Pull request by SergeCroise**
- **éle**ctrique
- s**élec**tion

### CODE REVIEW

**Review by emersion — APPROVED** [review]

**Review by theocrsb — APPROVED** [review]

**Comment by emersion** [comment]
Sounds like CI isn't happy about the commit title somehow… It sounds like it rejects digits in module names…

**Comment by emersion** [comment]
> Sounds like CI isn't happy about the commit title somehow… It sounds like it rejects digits in module names…

Fix for that in https://github.com/OpenRailAssociation/osrd/pull/8764

**Review by Uriel-Sautron — APPROVED** [review]
Thanks

**Comment by SergeCroise** [comment]
> > Sounds like CI isn't happy about the commit title somehow… It sounds like it rejects digits in module names…
> 
> Fix for that in #8764
Hello @emersion , I would like to understand how to merge this PR too:
https://github.com/OpenRailAssociation/osrd-ui/pull/392

**Review by SharglutDev — APPROVED** [review]
Thank you for contributing :)

For the check_commit, I think the test doesn't like your `:` after `i18n`

**Comment by emersion** [comment]
@SergeCroise Regarding PRs that we forget about: feel free to add a comment in the PR asking for attention, and I'd recommend joining our Matrix channel to communicate with us.

**Comment by emersion** [comment]
Can you rebase on top of #8764?

**Comment by SergeCroise** [comment]
hi @emersion , please review !

**Review by emersion — APPROVED** [review]
Thanks!

**Pull request merged**
