### PR TITLE
front: fix crash operationalPoints[0] is undefined

### LINKED ISSUE #8376: Frontend crash: operationalPoints[0] is undefined
### What happened?

When opening a specific scenario I got the following error page:

image

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. Import this [infra.json](https://github.com/user-attachments/files/16548976/infra.json)
2. Create a scenario with this infra
3. Import this [schedule.json](https://github.com/user-attachments/files/16548983/schedule.json)

Observe the error

### On which environments the bug occurs?

Local, Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

02781caf6fb315732a9067daebf49f1548d38415

### PR DESCRIPTION
**Pull request by clarani**
closes #8376

### CODE REVIEW

**Review by flomonster — APPROVED** [review]
Thanks!

**Review by theocrsb — APPROVED** [review]
LGTM and tested !

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested

**Review by kmer2016 — APPROVED** [review]
LGTM and tested !

**Pull request merged**
