### PR TITLE
core, editoast, front: stop using speed-limit tags' long names

### LINKED ISSUE #7977: etl-basic (+core): switch to the use of short ids for speedLimitTags
In order to allow for clearer and shorter interface:
- [ ] Imports from BASIC (simulations) + GAIA (infra) to OSRD must now use short ids of speedLimitTags instead of the current long names.
  - [x] PR opened on dags: https://github.com/osrd-project/osrd-dags/pull/417
  - [x] [etl-basic's PR](https://gitlab-repo-res.apps.eul.sncf.fr/dsir/groupedxs-dsir/04735/etl_basic/-/merge_requests/22) introducing speed-limit tags is reviewed to use short ids
- [x] Create, test and share a new PG dump with this data.
- [ ] Clean OSRD's code: https://github.com/OpenRailAssociation/osrd/pull/8417
  - [x] Cleanup bloated core code from #7903 (currently allows both short id or long name).
  - [x] Remove long names from static config-file
  - [x] Maybe remove default-speed too if unused is most likely in the future

Part of https://github.com/osrd-project/osrd-confidential/issues/364

### PR DESCRIPTION
**Pull request by bougue-pe**
* stop fallback on long-names (core)
* remove short-id extractors (front)
* adapt examples and small_infra

also remove default-speed, as it is unused

Resolves #7977 
🔍 ~This PR can be reviewed, but not merged~ 👇 

TODO:
- [x] Create a new dump beforehand and test it, then share it

### CODE REVIEW

**Review by shenriotpro — APPROVED** [review]
LGTM for tests/

**Review by woshilapin — APPROVED** [review]

**Comment by bougue-pe** [comment]
Fixed integration tests in https://github.com/OpenRailAssociation/osrd/pull/8417/commits/ddc2d2f7d87d6e24b5e1a8f27155db38fec26cd7 (@shenriotpro may re-review)

**Review by Erashin — APPROVED** [review]
Good job!

**Review by shenriotpro — APPROVED** [review]
Thanks

**Review by Maymanaf — APPROVED** [review]
LGTM for e2e tests

**Review by flomonster — APPROVED** [review]
LGTM (tested with new dump)

**Review by Math-R — APPROVED** [review]
LGTM :)

**Pull request merged**
