### PR TITLE
Bpt/editoast/parallel core requests

### LINKED ISSUE #6581: editoast: Make POST `/timetable/{id}` use all core workers
Editoast must make core use all its workers to have a more efficient timetable posting.

All items of the payload must be send at the same time and we should wait for the last one to finish to send the response to the client.

### PR DESCRIPTION
**Pull request by Castavo**
closes #6581

### CODE REVIEW

**Review by flomonster — APPROVED** [review]
LGTM

**Comment by bloussou** [comment]
Can you show an execution time comparison on the benchmark to check that we are not introducing bugs (loosing some trains) and having better performances ?

**Comment by Castavo** [comment]
@bloussou I've run the benchmark, no errors are added, and the two all-stops payloads now run in about 2min each :grin:

**Review by bloussou — APPROVED** [review]
Perfect !!

**Pull request merged**
