### PR TITLE
front: reorganize import train schedule scss

### LINKED ISSUE #5235: front: reorga scss of ImportTrainSchedule components
# Description

Move the relevant css files to the `ImportTrainSchedule` folder.

# Goal

Refacto front, improve code quality and readability.

# Acceptance criteria

- [x] The css files related to the `ImportTrainSchedule` component have been moved to the corresponding folder.

### LINKED ISSUE #5236: front: reorga scss of ManageTrainSchedule component
# Description

Move `styles/scss/applications/operationalStuides/_managetrainschedule.scss` and the relevant files to the `ManageTrainSchedule` folder.

# Goal

Refacto front, improve code quality and readability.

# Acceptance criteria

- [ ] The css files related to the `ManageTrainSchedule` component have been moved to the corresponding folder.

### PR DESCRIPTION
**Pull request by clarani**
closes #5235

### CODE REVIEW

**Comment by nicolaswurtz** [comment]
Something gets wrong ? :laughing: 
image

**Review by alexandredamiron — APPROVED** [review]

**Review by alexandredamiron — COMMENTED** [review]
Code seems correct but need to compare with previous

**Review by alexandredamiron — CHANGES_REQUESTED** [review]
Nicolas is right it does not fit

**Comment by alexandredamiron** [comment]
import-train-schedule-trainlist class is not applied. compilation ?

**Review by alexandredamiron — APPROVED** [review]

**Comment by alexandredamiron** [comment]
ok for me

**Review by Math-R — APPROVED** [review]

**Pull request merged**
