### PR TITLE
front: fix stdcm passage

### LINKED ISSUE #9655: front: stdcm stops at all vias, even if they are only "passage"
### What happened?

Try to create a stdcm with a via "PASSAGE" in debug mode. Check the GEV: the train stops at the via.

### What did you expect to happen?

The train should not stop if the via is only a waypoint and not a stop.

### How can we reproduce it (as minimally and precisely as possible)?

1. Use debug mode
2. Create a stdcm with a via (select Passage for the stop type)
3. Check the GEV

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by clarani**
closes #9655

### CODE REVIEW

**Comment by emersion** [comment]
Ouch :/ would it really be that much work to fix in editoast instead?

**Comment by clarani** [comment]
Right now, we just need a valid image so @bloussou can deploy on prod :/ I can ask on Element if someone can fix the bug in editoast

**Comment by emersion** [comment]
Alternative fix for the first commit (edit: that commit has now been dropped): https://github.com/OpenRailAssociation/osrd/pull/9656

**Comment by clarani** [comment]
I removed the last commit, related to the work schedules

**Review by Akctarus — CHANGES_REQUESTED** [review]
Tested, but got this error message: `Last step of stdcm request needs to be a stop`

last step duration is equal to `undefined`, and the request fails because of this. We'd have to add a `duration = 0` to this step

**Comment by clarani** [comment]
You're right, it's fixed

**Review by Akctarus — APPROVED** [review]
Tested, LGTM !

**Review by Math-R — APPROVED** [review]
Lgtm and tested !

**Pull request merged**
