### PR TITLE
front: add eslint rule to ban React.FC

### LINKED ISSUE #8663: front: add an eslint rule to ban the React.FC
### Description and goal

To harmonize the code base, we ban the React.FC

### Acceptance criteria

No React.FC in the code base anymore

### PR DESCRIPTION
**Pull request by clarani**
closes #8663

### CODE REVIEW

**Review by emersion — APPROVED** [review]
Nice!

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for this PR ! The eslint config doesn't catch `type FC` in `import React` (FC is still there in all IncompatibleConstraints components)

**Review by Caracol3 — COMMENTED** [review]
Lgtm

**Comment by emersion** [comment]
> Thank you for this PR ! The eslint config doesn't catch type FC in import React (FC is still there in all IncompatibleConstraints components)

Indeed! Added a rule for lone `FC` and dropped all remaining references (there were quite a few... !).

**Review by SharglutDev — APPROVED** [review]
Lgtm, thank you for the follow up @emersion :)

**Pull request merged**
