### PR TITLE
Front: ManageTrainSchedule: Fix translation in OperationalStudies

### LINKED ISSUE #5316: "Margins" in train creation should be called "Allowances"
### What happened?

Here :
image

### What did you expect to happen?

The english translation for "Marges" is `Allowances`, not `Margins`

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to any scenario
2. Open the train creation window

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: Windows 11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

495833d8

### PR DESCRIPTION
**Pull request by RomainValls**
- Changed "Margins" to "Allowances" in manageTrainSchedule.json

close #5316

### CODE REVIEW

**Review by SharglutDev — COMMENTED** [review]
Happy first PR ! If you could avoid to use uppercase in your commits :)

**Review by Yohh — APPROVED** [review]
LGTM :muscle:

**Review by flomonster — COMMENTED** [review]
Thanks for your contribution :tada: 

Can you reword your commit message to follow this [format](https://osrd.fr/en/docs/guides/contribute/code/#git-commit-style).

Note: Traduction can be fixed using transifex [here](https://explore.transifex.com/osrd/osrd/).

**Comment by RomainValls** [comment]
Changed my commit title to respect osrd conventions

**Review by sim51 — APPROVED** [review]

**Review by clarani — APPROVED** [review]
LGTM :tada:

**Pull request merged**
