### PR TITLE
front: fix warning in map

### LINKED ISSUE #9272: front: warning "A props object containing a "key" prop is being spread into JSX" in the console
### What happened?

When opening a view which contains a Map, a warning is displayed in the console:
Image

### What did you expect to happen?

No warning in the console

### How can we reproduce it (as minimally and precisely as possible)?

1. Open the reference map

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by clarani**
closes #9272

### CODE REVIEW

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Warning is still when entering a scenario :/

Capture d’écran 2024-10-10 à 09 11 54

**Review by Math-R — DISMISSED** [review]
still got warning to sorry

**Comment by clarani** [comment]
Sorry, I forgot to fix the warp Map. It should be fine now :+1:

**Comment by theocrsb** [comment]
I still have this error: 
image

**Comment by clarani** [comment]
Fixed, thanks @theocrsb :pray:

**Review by theocrsb — APPROVED** [review]
LGTM and tested :)

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job !

**Pull request merged**
