### PR TITLE
Add OpenApi annotations for views::infra::routes endpoints

### PR DESCRIPTION
**Pull request by leovalais**
refs #4580 #3625

### CODE REVIEW

**Review by flomonster — CHANGES_REQUESTED** [review]
I tried it and found a bug. We have a `404` `missing field infra_id` on the endpoint `/infra/8/routes/Detector/detecto.XXXXX/`

**Comment by leovalais** [comment]
Oops, thanks good catch 👀

**Review by SharglutDev — COMMENTED** [review]
Need to wait for the fix of this https://github.com/osrd-project/osrd/issues/6317 to be able to test the changes (will probably cause some conflicts)

**Review by Math-R — APPROVED** [review]
LGTM :)

**Review by flomonster — APPROVED** [review]
LGTM (Reviewed + Tested)

**Pull request merged**
