### PR TITLE
front: stdcm: fix typo

### PR DESCRIPTION
**Pull request by louisgreiner**
Fix typo, see Mock-up :

image

### CODE REVIEW

**Review by emersion — APPROVED** [review]

**Comment by emersion** [comment]
Pedantic note: "LMR" is not used in the open-source project, "STDCM" remains used there. "LMR" is strictly an SNCF-specific name.

**Review by JulesPeignier — APPROVED** [review]
nice.

**Comment by emersion** [comment]
It seems like your commit is missing a S-o-b trailer :P

**Review by SarahBellaha — APPROVED** [review]
💯

**Review by Math-R — APPROVED** [review]

**Review by theocrsb — APPROVED** [review]

**Comment by clarani** [comment]
You need to signup your commit ;)

**Review by RomainValls — APPROVED** [review]

**Pull request merged**
