### PR TITLE
front: Add minzoom = 5 for all editoast layers that missed a minZoom

### PR DESCRIPTION
**Pull request by nicolaswurtz**
All is said here : https://github.com/osrd-project/osrd/pull/5656#issue-1988125577

### CODE REVIEW

**Review by flomonster — COMMENTED** [review]
5 is great for tracks but I think we should have a higher value for other layers (what about `8` ?)

**Comment by nicolaswurtz** [comment]
@flomonster you're right, 8 is moreover a good choice, it's updated

**Review by flomonster — APPROVED** [review]
Great!

**Review by Akctarus — APPROVED** [review]
Tested and LGTM

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:

**Pull request merged**
