### PR TITLE
front: add placeholders in stdcm allowances inputs

### LINKED ISSUE #5549: front: add placeholders to stdcm inputs
Add placeholders to stdcm margin inputs. 
Image

⚠ this can be done only if the types are correct in editoast (see #5546)

### PR DESCRIPTION
**Pull request by clarani**
closes #5549 

image

### CODE REVIEW

**Review by Khoyo — APPROVED** [review]
Reviewed the Core change

**Review by eckter — APPROVED** [review]

**Review by SarahBellaha — APPROVED** [review]
LGTM :)

**Comment by kmer2016** [comment]
LGTM ! :)

**Comment by clarani** [comment]
Viewed with Nicolas and Thibaut, we removed the placeholders '...'

**Review by nicolaswurtz — APPROVED** [review]

**Pull request merged**
