### PR TITLE
front: fix GET interaction after a drag and drop (ts v2)

### LINKED ISSUE #7576: TSv2: Dragging a train on space time chart sometimes breaks the chart synchronizer
### What happened?

With trainschedule v2 activated, sometimes when dragging a train on the space time chart, the synchro between charts is lost and it doesn't know where the train has been moved resulting to the pointer at the wrong place.

Capture d’écran 2024-05-31 à 22 36 20

### What did you expect to happen?

This behaviour shouldn't happen.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to a scenario
2. Drag a train on the space time chart a few times until you see this behavior. 

### What operating system, browser and environment are you using?

- **Browser**: Firefox v126
- **OS**: macOS Sonoma 14.5
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 4ae7056

### PR DESCRIPTION
**Pull request by clarani**
closes #7576

### CODE REVIEW

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for the PR, I still have a strange behavior after dragging a train : 

https://github.com/OpenRailAssociation/osrd/assets/113104137/fc1b9d68-26ba-4c13-9102-08ffc111792f

**Review by Yohh — COMMENTED** [review]
nice, LGTM :muscle: 

good to see the pointer synchronization back

can you add a more explicit comment about why the timeline is disabled? (in fact, do we really need to keep this?)

image

**Comment by clarani** [comment]
I think we should discuss this with the POs. The component was broken and not used, so it was decided several months ago to comment it. I believe we don't need it anymore indeed

**Review by anisometropie — APPROVED** [review]

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job !

**Pull request merged**
