### PR TITLE
front: quick fix for speed label

### LINKED ISSUE #5496: Weird display next to the train on the map
### What happened?

This text here does not seem to mean anything.
image

Edit : it is supposed to be the time !

Also, maybe open another bug if necessary but the speed info sometimes ends up hidden by the train icon, as it's visible here :
image

### What did you expect to happen?

_The weird text should be removed_
Edit: No, it's supposed to be the time ! This regression needs to be fixed.

And the speed should not be hidden by the train.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the map after creating a train

### What operating system, browser and environment are you using?

- **Env**: rec-osrd.reseau.sncf.fr

### OSRD version (top right corner `Account` button > `Informations`)

1280353d6bb501ba1b4ad3c1ffe91927c6a6cfd0

### PR DESCRIPTION
**Pull request by alexandredamiron**
#closes #5496

This is a quick fix which will remove badly formatted time and give a shadow to the speed to it will remained visible

Correct behavior correction need a rewrite of train display logic

### CODE REVIEW

**Comment by SharglutDev** [comment]
Seems your changes are not taken into account when testing. You probably need to fix the conflict first.

**Review by SharglutDev — COMMENTED** [review]
Is the contrast enough ? Maybe we should ask the UX what he thinks

image

**Comment by thibautsailly** [comment]
The text-shadow should have a spread value to increase contrast:
`text-shadow: 0 0 0 rgba(255,255,255,0.83);`
Screenshot 2023-11-16 at 15 43 39

**Comment by alexandredamiron** [comment]
@thibautsailly I have to succes implementing that


Capture d’écran 2023-11-16 180814

**Comment by nicolaswurtz** [comment]
Thx ! But why remove time ? time is as necessary as speed, could you let (and correct format if needed) time ?

**Review by nicolaswurtz — APPROVED** [review]

**Comment by SharglutDev** [comment]
I still don't see @thibautsailly proposal

image

**Pull request merged**
