### PR TITLE
tests: fix small infra stations characteristics

### LINKED ISSUE #4375: Incoherent names in small infra
### What happened?

South-west Station is at the north of west station

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to cartography
2. Search for west station or south west station operational points
3. See that we're not lead where it's meant

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

ed02a3d3

### PR DESCRIPTION
**Pull request by louisgreiner**
Closes #4375 

- fix South West Station and West Station inversion
- replace station ch : "aa" -> "BV"
- make trigrams unique

-> to apply changes, run `./scripts/load-railjson-infra.sh small_infra tests/data/infras/small_infra/infra.json` or load the updated dump from sharepoint

### CODE REVIEW

**Comment by louisgreiner** [comment]
Should I update the version of [this file](python/railjson_generator/railjson_generator/schema/infra/infra.py), line 27 ?

**Review by flomonster — APPROVED** [review]
LGTM. You need to generate railjson examples though.

**Review by Castavo — APPROVED** [review]
Nice ! Thanks for the PR

The commit name is a bit vague tho, but it's good enough

**Review by bloussou — APPROVED** [review]
Perfect thanks a lot 🙏

**Review by Khoyo — APPROVED** [review]

**Pull request merged**
