### PR TITLE
front: adjusting map buttons

### PR DESCRIPTION
**Pull request by theocrsb**
closes https://github.com/osrd-project/osrd-confidential/issues/670

### CODE REVIEW

**Comment by Caracol3** [comment]
@theocrsb Just to confirm, on this PR there are only the tooltip changes? The infrastructure style modifications is postponed, right ?

**Comment by emersion** [comment]
Hm, seems like the top margin isn't 16px (seems to be 12px)…

out

Also I'd suggest changing `new-btn-map` to not have a top margin at all, only a bottom margin. That way we can apply a fixed 16px margin to its container without having to account for the inner one.

**Review by emersion — COMMENTED** [review]
Hm, seems like the top margin isn't 16px (seems to be 12px)…

out

Also I'd suggest changing `new-btn-map` to not have a top margin at all, only a bottom margin. That way we can apply a fixed 16px margin to its container without having to account for the inner one.

**Comment by theocrsb** [comment]
> @theocrsb Just to confirm, on this PR there are only the tooltip changes? The infrastructure style modifications is postponed, right ?

yes, the font and spacing

**Comment by theocrsb** [comment]
> Hm, seems like the top margin isn't 16px (seems to be 12px)…
> 
> out
> 
> Also I'd suggest changing `new-btn-map` to not have a top margin at all, only a bottom margin. That way we can apply a fixed 16px margin to its container without having to account for the inner one.

It's done :)

**Review by emersion — APPROVED** [review]
Looks good!

**Pull request merged**
