### PR TITLE
editoast: update all 'opentelemetry' related dependencies

### PR DESCRIPTION
**Pull request by woshilapin**
All Opentelemetry dependencies must be updated all at once (Dependabot can't really understand that). Here is the PR.

### CODE REVIEW

**Comment by woshilapin** [comment]
Seems like upgrading these dependencies means also that we need to upgrade minimum version of Rust

```
error: rustc 1.79.0 is not supported by the following package:
  axum-tracing-opentelemetry@0.19.1 requires rustc 1.80.0
Either upgrade rustc or select compatible dependency versions with
`cargo update <name>@<current-ver> --precise <compatible-ver>`
where `<compatible-ver>` is the latest version supporting rustc 1.79.0
```

Are we ok with such a change ?

**Comment by woshilapin** [comment]
Argh, installation of `grcov` doesn't work with Rust 1.80 because they didn't update `time` version... Brrrrr, should we start thinking of moving away of `grcov` ([no update on the subject since June](https://github.com/mozilla/grcov/issues/1187))? Until we decide, I believe removing `--locked` will do the trick...

**Review by Khoyo — APPROVED** [review]

**Comment by Khoyo** [comment]
>  no update on the subject since June? 

No commits on master since almost a year ago

**Review by flomonster — APPROVED** [review]
LGTM

**Review by Khoyo — APPROVED** [review]

**Comment by woshilapin** [comment]
I'm closing this PR since it doesn't work and it's already out of date anyway (see #9005 which will need to be fixed too).

**Pull request closed without merging**
