### PR TITLE
editoast: fix search_signal INSERT trigger

### LINKED ISSUE #7605: Signal search in cartography doesn't work
### What happened?

I want to research a Signal but the search doesn't work -> no results
- the search with Line doesn't work (whereas it's working with the main Line search)
- the search with Signal doesn't work

image
image

## Whereas search with main Line search is working : 
image

### What did you expect to happen?

There should be some suggestions of lines and signals

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to Cartographie
2. Click on Rechercher 
3. Click on Signal
4. Tap something in the Line or Signal input field

### What operating system, browser and environment are you using?

- **Browser**: Chrome version 124.0.6367.202
- **OS**: Windows
- **Env**: staging

### OSRD version (top right corner `Account` button > `Informations`)

staging 625d185

### PR DESCRIPTION
**Pull request by emersion**
To keep the search_signal table in sync with new rows inserted in
the infra_object_signal table, we have an automatically-generated
trigger in place. This trigger performs a JOIN on the
infra_layer_signal table. However, when a row is inserted in
infra_object_signal, no matching row has been inserted into
infra_layer_signal yet and the JOIN returns an empty result.

The JOIN is necessary to populate two rows, sprite_signaling_system
and sprite. However, instead of duplicating these fields in
search_signal, we can just grab them from the infra_layer_signal
table with a JOIN when SELECT'ing from search_signal.

Drop the sprite_signaling_system/sprite fields, and drop the JOIN
in the trigger.

The up.sql migration has been generated by
`editoast search make-migration`. The down.sql migration has been
copied from 2023-10-18-164705_logical_signals_search/up.sql so that
downgrading restores the old search_signal table and triggers,
rather than dropping it.

Closes: https://github.com/OpenRailAssociation/osrd/issues/7605

### CODE REVIEW

**Review by flomonster — APPROVED** [review]
LGTM

**Review by leovalais — COMMENTED** [review]
I haven't tested it yet. You'll need to generate a migration for this change (`diesel-cli` + `editoast search --help`).

Thanks for fixing this! :D

**Review by flomonster — APPROVED** [review]
Tested :ok_hand:

**Review by leovalais — APPROVED** [review]
Tested! 🚀

**Pull request merged**
