### PR TITLE
front: scenario page size adjustment

### LINKED ISSUE #9218: Unnecessary spacing in the scenario page
### What happened?

image

### How can we reproduce it (as minimally and precisely as possible)?

Go to scenario page
See spacing at bottom of page

### On which environments the bug occurs?

Local, Dev (SNCF), Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

87a6547

### PR DESCRIPTION
**Pull request by theocrsb**
closes #9218

### CODE REVIEW

**Comment by emersion** [comment]
Seems like the conflict infobox doesn't stick to the bottom when there are only a few trains. See the blank space at the bottom:

out

**Comment by emersion** [comment]
And with a lot of trains it seems there is a missing padding at the bottom:

out

**Comment by theocrsb** [comment]
> Seems like the conflict infobox doesn't stick to the bottom when there are only a few trains. See the blank space at the bottom:
> 
> out

This behavior must be fixed by this [PR](https://github.com/OpenRailAssociation/osrd/pull/9219)

**Comment by theocrsb** [comment]
> And with a lot of trains it seems there is a missing padding at the bottom:

image
I didn't put a `padding bottom` to prepare the next PR on the redesign of the conflict list.

**Comment by emersion** [comment]
> I didn't put a `padding bottom` to prepare the next PR on the redesign of the conflict list. 

I see. I wonder if we really want to have a weird-looking UI during the transition though. (I suspect we will need to do a bunch more work anyways to adapt to the new UI, e.g. reorganizing the HTML.)

**Comment by theocrsb** [comment]
> > I didn't put a `padding bottom` to prepare the next PR on the redesign of the conflict list.
> 
> I see. I wonder if we really want to have a weird-looking UI during the transition though. (I suspect we will need to do a bunch more work anyways to adapt to the new UI, e.g. reorganizing the HTML.)

You're right, it's done.

**Review by emersion — APPROVED** [review]
LGTM and works!

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested

**Pull request merged**
