### PR TITLE
front: update electrical profile set id in store when loading scenario

### PR DESCRIPTION
**Pull request by Castavo**

### CODE REVIEW

**Review by emersion — APPROVED** [review]

**Comment by emersion** [comment]
(Sounds like #8167 introduced `updateElectricalProfileSetId()` but never called it.)

**Comment by Castavo** [comment]
@emersion When introduced by #8167, it was called in ScenarioV2.tsx ([see here](https://github.com/OpenRailAssociation/osrd/pull/8167/files#diff-4af9239e58b8a61cd057ec66d49ba3cfb30e1251bf97dc69e292a43dfffca383))
I'd say it's a later refactor which removed it

**Comment by emersion** [comment]
Aha, this file was collapsed in the GitHub UI, my bad.

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark: (not tested)

**Pull request merged**
