### PR TITLE
docker: add back build cache mounts

### PR DESCRIPTION
**Pull request by Khoyo**

### CODE REVIEW

**Comment by emersion** [comment]
The CI in this PR takes more than 20min - do we expect subsequent CI runs to take significantly less time than that or not?

**Comment by Khoyo** [comment]
~~I'm checking. This is mostly for local speedup, I wasn't expecting a speedup in the CI. It seems to go reasonably fast anyway when not rebuilding the whole backend (8min with a random editoast change) ~~

It is now disabled during CI builds.

**Review by ghost — APPROVED** [review]
Yes, that will help developers a lot, thanks !

**Review by emersion — APPROVED** [review]
LGTM!

**Review by flomonster — APPROVED** [review]
LGTM

**Pull request merged**
