### PR TITLE
front: bump nge version to 2.9.11

### PR DESCRIPTION
**Pull request by louisgreiner**
Bumps to 2.9.11

Integrates a [fix](https://github.com/osrd-project/netzgrafik-editor-frontend/pull/6) from fork

### CODE REVIEW

**Review by Yohh — APPROVED** [review]
don't forget sign-off

**Review by emersion — APPROVED** [review]
LGTM

Note, this will conflict with https://github.com/OpenRailAssociation/osrd/pull/9169

**Review by emersion — CHANGES_REQUESTED** [review]
The `package-lock.json` file has not been updated. You need to run `npm install` to update it.

**Review by emersion — APPROVED** [review]
LGTM!

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:

**Pull request merged**
