### PR TITLE
front: fix simulation results width on wide screen

### LINKED ISSUE #9959: front: wrong width on wide screen
### What happened?

actually on screen resolution superior to 1280p the simulation results looks like this:

Image

### What did you expect to happen?

the simulation results should stretch to the maximum width available:

Image

### How can we reproduce it (as minimally and precisely as possible)?

create a simulation with a screen resolution superior to 1280p

### On which environments the bug occurs?

Recette (SNCF), Local, Dev (SNCF), Integration (SNCF)

### On which browser the bug occurs?

Firefox, Google Chrome, Microsoft Edge, Safari, Opera

### OSRD version (top right corner `Account` button > `Informations`)

-

### PR DESCRIPTION
**Pull request by Yohh**
close #9959

### CODE REVIEW

**Comment by Yohh** [comment]
NB: I m not sure that the max-width is really usefull at all, even in lower resolutions

**Comment by SharglutDev** [comment]
> NB: I m not sure that the max-width is really usefull at all, even in lower resolutions

Probably. Doesn't it achieve the same result if you remove `max-width` totally ?

**Comment by Yohh** [comment]
> > NB: I m not sure that the max-width is really usefull at all, even in lower resolutions
> 
> Probably. Doesn't it achieve the same result if you remove `max-width` totally ?

it releases the `col` classes, so the width fit responsively, that seems much better to me, I added the media query only because I thought it was a mockup criteria

in fact, combining `col` and min/max-width seems to lack consistence

**Comment by SharglutDev** [comment]
Totally missread the issue. I thought we want to stretch the results, not the sidebar. Your solution seems fine to me.

We should probably get rid off the `col`s when we work more on the responsive design.

**Review by SharglutDev — APPROVED** [review]

**Comment by Yohh** [comment]
on the contrary, `col`s are more responsive than using `px`, if I remove max-width and min-width totally the behavior seems fine:


https://github.com/user-attachments/assets/12639d16-5c1f-481b-9c1d-79ed4ea75926

**Comment by SharglutDev** [comment]
> on the contrary, `col`s are more responsive than using `px`, if I remove max-width and min-width totally the behavior seems fine:
> Screencast.From.2024-12-05.14-23-05.mp4

Yes but as you mentioned, the mockup specifies that the default sidemenu width should be 432px

Capture d’écran 2024-12-05 à 15 02 54

**Comment by Yohh** [comment]
> Yes but as you mentioned, the mockup specifies that the default sidemenu width should be 432px

ok go for it

**Comment by Caracol3** [comment]
I would also tend to prefer the use of col in the application. I find it more responsive. Though, for pixel-perfect concerns, I understand that pixels are used, but the question might be whether Thibaut is familiar with using col. If not, maybe it’s up to us to adapt the design by converting pixels to columns and get it validated by Thibaut afterward.

**Comment by Caracol3** [comment]
Lgtm (tested)

**Review by Caracol3 — APPROVED** [review]
lgtm (tested)

**Comment by SharglutDev** [comment]
> I would also tend to prefer the use of col in the application. I find it more responsive. Though, for pixel-perfect concerns, I understand that pixels are used, but the question might be whether Thibaut is familiar with using col. If not, maybe it’s up to us to adapt the design by converting pixels to columns and get it validated by Thibaut afterward.

We totally should have a discussion with him next time. I added it in the discussions list for next front meeting.

**Pull request merged**
