### PR TITLE
front: set default tolerances in the store

### LINKED ISSUE #9803: The default tolerance value is not taken into account
### What happened?

The default tolerence value is not charged in the payload

Image

### What did you expect to happen?

The default tolerence value -30/+30 should charged in the Payload

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to LMR
2. Start a simulation without changing the tolerence
3. Observe the payload 

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox, Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

6be0604

### PR DESCRIPTION
**Pull request by clarani**
closes #9803

### CODE REVIEW

**Review by theocrsb — CHANGES_REQUESTED** [review]
Not working for me :/ 
image

**Comment by theocrsb** [comment]
> Not working for me :/ image

After cleaning the local storage, it works well for me

**Review by theocrsb — APPROVED** [review]
LGTM and tested !

**Review by Math-R — APPROVED** [review]
lgtm !

**Pull request merged**
