### PR TITLE
root: remove trash file

### PR DESCRIPTION
**Pull request by flomonster**

### CODE REVIEW

**Review by eckter — APPROVED** [review]

**Review by Khoyo — APPROVED** [review]
Wait, this isn't a real lockfile ? Oo

**Comment by multun** [comment]
Nop, the real one is in the front folder

**Comment by multun** [comment]
@flomonster can you add a .gitignore entry too?

**Comment by Khoyo** [comment]
> @flomonster can you add a .gitignore entry too?

done #2662

**Comment by flomonster** [comment]
It's kind of weird to add it cause their is no reason to have a lock file here

**Comment by Khoyo** [comment]
The fact that it was committed once means it's a mistake that can and does happen ;)

**Pull request merged**
