### PR TITLE
Add security file

### PR DESCRIPTION
**Pull request by flomonster**

### CODE REVIEW

**Comment by emersion** [comment]
Note, seems like this is copied over from https://github.com/electron/electron/blob/main/SECURITY.md

**Comment by emersion** [comment]
- Security policies typically indicate which versions are currently supported.
- Might be worth mentioning that security issues should not be reported through public GitHub issues.

**Review by Khoyo — APPROVED** [review]
Didn't know github had that feature, that's really nice

**Review by ghost — APPROVED** [review]

**Review by bloussou — APPROVED** [review]
✅

**Review by emersion — APPROVED** [review]

**Review by clarani — APPROVED** [review]

**Pull request merged**
