### PR TITLE
fixup! editoast: adapt endpoint for routes from switches

### PR DESCRIPTION
**Pull request by woshilapin**
A proposition of improvement about a huge closure in #7239.

⚠️ Note that this PR does not target `dev` but the branch of the #7239 PR (and the commit is a fixup commit).

### CODE REVIEW

**Review by leovalais — APPROVED** [review]
Thanks! The CI's unhappy though :p

**Comment by woshilapin** [comment]
@leovalais Should we make the _commit check_ only on PR targeting `dev`? In this case, I'll probably just push to @SarahBellaha's branch directly and just forget about the current PR.

**Comment by leovalais** [comment]
Probably easier sure. I'm all for relaxing the commit check because the workflow's legit here and the check gets in the way.

**Comment by woshilapin** [comment]
Just pushing on Sarah's branch made Github understand it was merged. nice!

**Pull request merged**
