### PR TITLE
front: use the new map style

### LINKED ISSUE #8908: front: use the new map style
### Who would benefit from this feature?

End users

### What is this feature about?

Use the new style of the map, designed by Thibaut

### Why is this feature valuable?

It will harmonize the app UI

### Anything else people should know?

Thibaut

### PR DESCRIPTION
**Pull request by clarani**
closes #8908 

The new mapStyle was provided by Thibaut

image

### CODE REVIEW

**Comment by thibautsailly** [comment]
Would it be possible to see the map for the Bretagne area, and for the whole of France? It was not possible to view rail tracks at this scale in the tool I used to edit the theme (Maputnik). Thank you!

**Comment by clarani** [comment]
Yes of course: 
image

**Comment by Caracol3** [comment]
I don't know if it's intentional, but now, at initialization and at least up to zoom level 2, we have a less detailed map than before with the same display settings.
At first glance, I find it less visually appealing without an additional level of detail. It seems a bit empty. But this is subjective. Maybe the decision was made to focus on displaying tracks rather than forests (which would be a logical choice 😆).

on dev at initialization:
image

On your branch same zoom level:
image(1)

**Comment by thibautsailly** [comment]
It was absolutely intentional to remove details from the map so it's more focused on the infrastructure. That doesn't mean we can't work on the less appealing aspect (the green areas are not forests but national parks). We should talk about it together in front of the map when we can.
It seems that the background color isn't the same, here is a screenshot of the theme in Maputnik:
image
background is `rgb(246, 245, 241)`

**Comment by clarani** [comment]
I changed the color of the background:
image

**Review by SarahBellaha — APPROVED** [review]

**Review by SarahBellaha — APPROVED** [review]
Lgtm :)

**Review by Caracol3 — APPROVED** [review]
lgtm

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested ! Really nice :) But we should wait after the demo to merge I think (checked with @flomonster)

**Pull request merged**
