### PR TITLE
Bump ui from 0.0.55 to 0.0.56

### PR DESCRIPTION
**Pull request by achrafmohye**

### CODE REVIEW

**Review by theocrsb — CHANGES_REQUESTED** [review]
I think you didn't want to add the `yarn.lock` file

**Review by theocrsb — APPROVED** [review]

**Comment by SharglutDev** [comment]
@Yohh Do you know why we lose some packages from osrd-ui in lock file ?

**Comment by Yohh** [comment]
> @Yohh Do you know why we lose some packages from osrd-ui in lock file ?

good question, maybe someone did clean osrd-ui dependencies before the release

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested

**Review by Maymanaf — APPROVED** [review]
LGTM for e2e-tests

**Pull request merged**
