### PR TITLE
python: bump osrd-schemas version

### PR DESCRIPTION
**Pull request by shenriotpro**

### CODE REVIEW

**Review by leovalais — APPROVED** [review]
LGTM

**Review by flomonster — APPROVED** [review]
Lgtm

**Comment by Khoyo** [comment]
I think the latest change also require a bump in railjson generator, no?

**Comment by flomonster** [comment]
> I think the latest change also require a bump in railjson generator, no?

You are right, actually I don't know if the railjson-generator is still used but I don't think so. Maybe we should drop this component?

**Comment by Khoyo** [comment]
> You are right, actually I don't know if the railjson-generator is still used but I don't think so. Maybe we should drop this component?

It's how we generate tiny-infra, small-infra, etc.

(btw, I believe you also need to bump the railjson-generator lockfile, otherwise poetry might fail to bump the dependency if it's not the first install)

**Pull request merged**
