### PR TITLE
front: remove infra loader while in macro mode

### LINKED ISSUE #9271: Micro/Macro toggle button is available while infra is loading
### What happened?

While infra is loading, we can still switch in Macro mode (but not the way back)

Image

### What did you expect to happen?

disable the button while infra is loading

### How can we reproduce it (as minimally and precisely as possible)?

1. open scenario with infra france
2. switch to macro

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging 1482e8c

### PR DESCRIPTION
**Pull request by RomainValls**
closes #9271

### CODE REVIEW

**Comment by emersion** [comment]
I'm not a fan of this solution because nothing in NGE requires a loaded infra. Couldn't we hide the loader while switched to NGE?

cc @louisgreiner

**Review by theocrsb — COMMENTED** [review]
I think isInfraLoaded is true when `infra.state === TRANSIENT_ERROR`. If so, is this the expected behavior?

**Comment by louisgreiner** [comment]
@emersion, I agree NGE does not need this infra, but it can trigger simulations. Are simulations independent of the infra ? Wouldn't it lead to potential errors if a user create new nodes and trains on it ?

If the behaviour of NGE is safe even without loaded infra, we could just disable the loading screen and allow the user to use the Macro mode (which is very cool actually, while the infra is loading)

**Comment by emersion** [comment]
> but it can trigger simulations

It shouldn't trigger simulations. NGE edits fill up a queue of pending operations which is flushed when the user goes back to micro mode. Only then the simulation should be fired up.

**Comment by louisgreiner** [comment]
Then we can keep macro mode enabled while infra is loading (and remove the loading screen in macro mode)

**Comment by RomainValls** [comment]
Removed the loader while in macro mode, thanks 👍

**Review by emersion — APPROVED** [review]
Looks good! Can you squash your commits together into a single one?

**Pull request merged**
