### PR TITLE
docker: use dev profile instead of release for docker-compose

### PR DESCRIPTION
**Pull request by emersion**
docker-compose is used for development. Use the "dev" profile instead of "release" to speed up builds.

### CODE REVIEW

**Comment by emersion** [comment]
Err, it sounds like `cargo install` re-builds in `release` mode…

**Comment by emersion** [comment]
There, fixed.

**Review by younesschrifi — APPROVED** [review]
LGTM ! 👍🏽

**Review by Khoyo — APPROVED** [review]

**Review by leovalais — APPROVED** [review]
Thanks! (not tested)

**Pull request merged**
