### PR TITLE
editoast: populate InternalError status/context when unparsable

### PR DESCRIPTION
**Pull request by emersion**
Add more metadata to the InternalError when it's not a proper JSON-encoded StandardCoreError.

### CODE REVIEW

**Review by woshilapin — APPROVED** [review]
Thank you.

**Comment by leovalais** [comment]
Thanks. This module is being rewritten in #8048. We'll likely be able to keep this change in the new version, however since we'll communicate with core using message queues, the `url` part of the request has become an implementation detail. We probably don't want to rely on that field of the error. What are you needing this change for?

**Comment by emersion** [comment]
Nothing in particular TBH, just manual inspection and extracting metadata from errors while debugging. Happy to close this PR if this chunk of code is on the chopping block anyways.

**Comment by leovalais** [comment]
Oh no, it's fine. My point was that we shouldn't rely on the `url` programmatically, but like you said it's always useful for debugging! 😄

**Pull request merged**
