### PR TITLE
tests: fix pytype errors in integration tests

### LINKED ISSUE #5396: tests: fix pytype errors in integration tests
### Description and goal

We're currently trying pytype, and there are a few typing errors to fix.
Then we can advertise/enforce it, and start working on other packages.

### Acceptance criteria

`poetry run pytype .` shouldn't return errors

### PR DESCRIPTION
**Pull request by shenriotpro**
closes https://github.com/osrd-project/osrd/issues/5396

### CODE REVIEW

**Comment by eckter** [comment]
There's one last error on the test module: `File "tests/tests/test_with_fuzzer.py", line 11, in <module>: Can't find module 'fuzzer'. [import-error]`

Ideally we should probably find a way to get rid of this `sys.path.append`, but in the meantime we can add `# pytype: disable=import-error` on the import line

**Comment by shenriotpro** [comment]
I don't have this error, could you give more details te reproduce?

**Comment by eckter** [comment]
That's what I get when I run `poetry run pytype`

```
eckter@desktop-ubuntu:~/osrd/tests$ poetry run pytype
Computing dependencies
/home/eckter/.cache/pypoetry/virtualenvs/tests-o4eXNnca-py3.10/lib/python3.10/site-packages/urllib3/contrib/socks.py:50: DependencyWarning: SOCKS support in urllib3 requires the installation of optional dependencies: specifically, PySocks.  For more information, see https://urllib3.readthedocs.io/en/latest/contrib.html#socks-proxies
  warnings.warn(
Analyzing 21 sources with 0 local dependencies
ninja: Entering directory `.pytype'
[1/1] check tests.test_with_fuzzer
FAILED: /home/eckter/osrd/tests/.pytype/pyi/tests/test_with_fuzzer.pyi 
/home/eckter/.cache/pypoetry/virtualenvs/tests-o4eXNnca-py3.10/bin/python -m pytype.single --imports_info /home/eckter/osrd/tests/.pytype/imports/tests.test_with_fuzzer.imports --module-name tests.test_with_fuzzer --platform linux -V 3.10 -o /home/eckter/osrd/tests/.pytype/pyi/tests/test_with_fuzzer.pyi --analyze-annotated --nofail --quick /home/eckter/osrd/tests/tests/test_with_fuzzer.py
File "/home/eckter/osrd/tests/tests/test_with_fuzzer.py", line 11, in <module>: Can't find module 'fuzzer'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
ninja: build stopped: subcommand failed.
Leaving directory '.pytype'
```

**Comment by shenriotpro** [comment]
Interesting, so `pytype` and `pytype .` are not equivalent.

**Review by eckter — APPROVED** [review]

**Pull request merged**
