### PR TITLE
front: upgrade prettier

### PR DESCRIPTION
**Pull request by emersion**
This requires a small change in InfraErrorsList.

### CODE REVIEW

**Review by Caracol3 — COMMENTED** [review]
I thought we shouldn't push the yarn.lock. 
Is there a reason to do so ?

**Comment by emersion** [comment]
The `yarn.lock` is already in Git, this PR doesn't change anything about this :P 

It's important to include `yarn.lock` in Git for reproducibility: thanks to that file we're all using the same version of each dependency. Hence, if a dependency upgrade introduces a bug or changes behavior (as seen in this PR: prettier output changes), we all see the same thing and our production deployment doesn't burn without us noticing.

Does this make sense?

**Comment by Caracol3** [comment]
Totally ! Thanks, for the details 🙏

**Review by Caracol3 — APPROVED** [review]
lgtm (tested)

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, thank you. Maybe we should warn on matrix that we all need to "yarn install" to have last rules of prettier.

**Comment by emersion** [comment]
Yeah. Restarting the front container is necessary after pulling any kind of dependency change.

**Pull request merged**
