### PR TITLE
front: upgrade minor dependencies

### LINKED ISSUE #9257: front: minor upgrade for several dependencies
upgrade i18n from 23.5.1 to 23.8.2

### PR DESCRIPTION
**Pull request by Yohh**
close #9257

### CODE REVIEW

**Review by clarani — APPROVED** [review]
LGTM :white_check_mark:

**Comment by emersion** [comment]
Could we also upgrade these while at it?

out

**Comment by Yohh** [comment]
> Could we also upgrade these while at it?
> 
> out

sure, that was my intention

done

**Review by emersion — APPROVED** [review]
LGTM!

**Pull request merged**
