### PR TITLE
Bye bye openapi_legacy.yaml 🥳🥳

### PR DESCRIPTION
**Pull request by leovalais**
FINALLY

* removes openapi_legacy
* drop merging support
* a few fixes that went unnoticed

### CODE REVIEW

**Review by Uriel-Sautron — APPROVED** [review]
Good work, thank you !!!
LGTM, I only reviewed the front-end part.

**Review by Tristramg — APPROVED** [review]
I didn’t test it (my stack is currently a wreck), but it looks good to me. Congratulations!

**Review by flomonster — APPROVED** [review]
LGTM (reviewed + tested)

**Review by SharglutDev — APPROVED** [review]
Lgtm for front part

**Pull request merged**
