### PR TITLE
front, ci: bump node js (18 -> 20)

### LINKED ISSUE #8088: front: bump node
### Description and goal

NodeJS 18 is in maintaince, it will be deprecated next year. We need to use nodeJS 20.
image

### Acceptance criteria

- [ ] use nodeJS 20

### PR DESCRIPTION
**Pull request by clarani**
closes #8088

### CODE REVIEW

**Comment by anisometropie** [comment]
We should have a `.nvmrc` file to sync the dev environment with the docker containers 
https://github.com/nvm-sh/nvm#nvmrc

`@types/node` major version should also match, but we already had `"^20.11.16"`

**Review by ghost — APPROVED** [review]
CI's working properly, tests are passing. I think it should be fine to merge this.

**Comment by ghost** [comment]
> We should have a `.nvmrc` file to sync the dev environment with the docker containers https://github.com/nvm-sh/nvm#nvmrc
> 
> `@types/node` major version should also match, but we already had `"^20.11.16"`

Done.

**Review by anisometropie — APPROVED** [review]

**Review by clarani — COMMENTED** [review]
LGTM

**Review by SharglutDev — APPROVED** [review]
Lgtm (not tested)

**Pull request merged**
