### PR TITLE
editoast: remove serde default from project and study

### LINKED ISSUE #6773: Certain fields must not have default values in studies and projects
### What happened?

For certain String fields, when the front sets a value to None in the StudyCreateForm, the back, by default, enters an empty character string in the database.

### What did you expect to happen?

This is not consistent with the StudyPatchForm. 
The front end should send empty strings and the back end should remove the default values.

### How can we reproduce it (as minimally and precisely as possible)?

1. Open the form for creating a study
2. Let the description field empty
3. Save the study
 

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

d45ca39

### PR DESCRIPTION
**Pull request by Wadjetz**
- [x] The frontend already send empty strings
- [x] Fix openapi
- [x] Fix tests

close #6773

### CODE REVIEW

**Review by younesschrifi — APPROVED** [review]
LGTM

**Review by Tguisnet — CHANGES_REQUESTED** [review]
You need to Adapt OpenAPI and tests, otherwise it looks good to me for the editoast part.

**Review by hamz2a — APPROVED** [review]
LGTM.

**Review by Tguisnet — APPROVED** [review]
lgtm

**Review by woshilapin — APPROVED** [review]
Nice improvement (and bug fix) 🎉

**Review by SharglutDev — APPROVED** [review]
Lgtm

**Pull request merged**
