### PR TITLE
front: rename variable from French to English

### PR DESCRIPTION
**Pull request by ghost**
Resolves #[7891](https://github.com/OpenRailAssociation/osrd/issues/7891)

### CODE REVIEW

**Comment by emersion** [comment]
Thanks for submitting a pull request!

The idea looks good, but I wonder if `searchRollingStock`, `searchStock` or just `search` would be a better pick? We use the term "rolling stock" as the translation of the French word "matériel roulant". It should be clear enough from the function name `useFilterRollingStock()` that this is about rolling stocks (and most other variable names don't have "rolling stock" in their name).

What do you think?

**Comment by ghost** [comment]
> Thanks for submitting a pull request!
> 
> The idea looks good, but I wonder if `searchRollingStock`, `searchStock` or just `search` would be a better pick? We use the term "rolling stock" as the translation of the French word "matériel roulant". It should be clear enough from the function name `useFilterRollingStock()` that this is about rolling stocks (and most other variable names don't have "rolling stock" in their name).
> 
> What do you think?

Thank you, Emersion, for the warm welcome and the translation explanation. 

Yes, I agree with you that `searchMaterial` is not the best variable name. My vote is for `searchStock`, since that seems to most adhere to the codebase naming convention & provides more clarity than `search`.

**Comment by emersion** [comment]
Works for me!

**Review by emersion — APPROVED** [review]
Looks good to me :)

**Review by SharglutDev — COMMENTED** [review]
Hi turnerian2004, thanks for contributing to osrd and spotting this translation issue !

My vote goes to `searchRollingStock`. I think `searchStock` is a little confusing and feels like we don't want to bother to put the whole "rolling stock" word in the variable ? Moreover, everywhere in the app, we use `rollingStock` to refer to the train traction "material".

**Review by SharglutDev — APPROVED** [review]
Lgtm

**Comment by ghost** [comment]
Hi SharglutDev! Thank you, also, for the warm welcome. 

I started to type a reply to your comment but fell asleep before the posting the comment and the pr was merged lol

**Comment by ghost** [comment]
> Hi SharglutDev! Thank you, also, for the warm welcome.
> 
> I started to type a reply to your comment but fell asleep before the posting the comment and the pr was merged lol

@SharglutDev 😊😊😊

**Comment by SharglutDev** [comment]
Haha don't worry, thank you again for contributing, don't work too much !

**Pull request merged**
