### PR TITLE
front: fix crash when hitting the user settings

### LINKED ISSUE #7318: front: crash when hitting the user settings
### What happened?

When hitting the user settings button on Home page or Rolling stock editor page, the app crashes

### What did you expect to happen?

No crash

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to Home
2. Click on user settings

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Nixos v22.11
- **Env**: Local

### OSRD version (top right corner `Account` button > `Informations`)

dev 11da135

### PR DESCRIPTION
**Pull request by clarani**
close #7318

### CODE REVIEW

**Review by emersion — APPROVED** [review]
Indeed, no need to go through context after all!

LGTM :)

**Review by kmer2016 — APPROVED** [review]
LGTM !

**Review by SarahBellaha — APPROVED** [review]
LGTM :)

**Review by Math-R — APPROVED** [review]
lgtm

**Pull request merged**
