### PR TITLE
front: fix height of rollingstock editor spreadsheet for matching wit…

### LINKED ISSUE #7315: Unnecessary vertical scroll in speed-effort curves tab
### What happened?

When editing a rolling stock curve with at least 15 rows, an unwanted vertical scroll appears.

image

 

### What did you expect to happen?

It should not scroll vertically

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to rolling stock editor
2. Edit a train
3. Go to speed-effort curves tab
4. Have at least 15 rows

You can observe that the `Confirm` button is hidden (you have to scroll)

### What operating system, browser and environment are you using?

- **Browser**: Firefox v125
- **OS**: Nixos v23.11
- **Env**: DgexSol

### OSRD version (top right corner `Account` button > `Informations`)

11da135

### PR DESCRIPTION
**Pull request by theocrsb**
closes #7315

### CODE REVIEW

**Review by Akctarus — APPROVED** [review]
Tested, works well !

**Comment by kmer2016** [comment]
You are solution works with 15 rows. However, if we have more rows, like 35, a scroll bar appears. From what I understand about the [issue](https://github.com/OpenRailAssociation/osrd/issues/7315) the main problem is that the confirm button is hidden when there are many rows in the grid. So, I believe a better solution would be to move the container of the confirm/cancel buttons to a non-scrollable area.

**Review by kmer2016 — CHANGES_REQUESTED** [review]
You are solution works with 15 rows. However, if we have more rows, like 35, a scroll bar appears. Generally with overflow problem, add the height/width don't solve the problem, it deplaceFrom what I understand about the [issue](https://github.com/OpenRailAssociation/osrd/issues/7315) the main problem is that the confirm button is hidden when there are many rows in the grid. 
Generally, when dealing with overflow issues like this, simply increasing the height or width doesn't actually solve the problem; it just shifts it. So, I believe that a better solution would be to place the confirm/cancel buttons in a non-scrollable container, ensuring they remain visible regardless of the number of rows and apply the `overflow` on the area which can be expanded.

**Comment by kmer2016** [comment]
>You are solution works with 15 rows. However, if we have more rows, like 35, a scroll bar appears. Generally with overflow problem, add the height/width don't solve the problem, it deplaceFrom what I understand about the https://github.com/OpenRailAssociation/osrd/issues/7315 the main problem is that the confirm button is hidden when there are many rows in the grid.
Generally, when dealing with overflow issues like this, simply increasing the height or width doesn't actually solve the problem; it just shifts it. So, I believe that a better solution would be to place the confirm/cancel buttons in a non-scrollable container, ensuring they remain visible regardless of the number of rows and apply the overflow on the area which can be expanded.

I have checked the buttons' separate container, and I think you can simply apply overflow: auto to the tab container.

**Review by kmer2016 — APPROVED** [review]
LGTM and tested !

**Comment by theocrsb** [comment]
> > You are solution works with 15 rows. However, if we have more rows, like 35, a scroll bar appears. Generally with overflow problem, add the height/width don't solve the problem, it deplaceFrom what I understand about the #7315 the main problem is that the confirm button is hidden when there are many rows in the grid.
> > Generally, when dealing with overflow issues like this, simply increasing the height or width doesn't actually solve the problem; it just shifts it. So, I believe that a better solution would be to place the confirm/cancel buttons in a non-scrollable container, ensuring they remain visible regardless of the number of rows and apply the overflow on the area which can be expanded.
> 
> I have checked the buttons' separate container, and I think you can simply apply overflow: auto to the tab container.

You're right, it's done

**Pull request merged**
