### PR TITLE
Using isoDateWithTimezoneToSec for timezone-aware conversions

### LINKED ISSUE #8933: Train schedule created notification display wrong departure time
### What happened?

image

image

I created a train schedule that starts at 08:00:00 but the notification (bottom right) displays 06:00:00

 However, the created train schedule has the right departure time.

image

### What did you expect to happen?

_No response_

### How can we reproduce it (as minimally and precisely as possible)?

1. Create train schedule
2. notice

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging fbf8e3e

### PR DESCRIPTION
**Pull request by theocrsb**
Closes #8933

### CODE REVIEW

**Review by Akctarus — DISMISSED** [review]
This correction creates a new bug: the train created is set to `1/01/1970 01:00:00 `. I think the bug you're trying to correct is due to a miscalculation of the time zone, since the delay between the notification and the actual departure time is only 2 hours.

**Review by Akctarus — CHANGES_REQUESTED** [review]
see last comment

**Comment by theocrsb** [comment]
Ok I didn't see that I also modify the train creation date. I used the timezone only for the notification. Thanks for your feedback

**Review by Akctarus — APPROVED** [review]
Tested, LGTM :)

**Review by clarani — APPROVED** [review]
LGTM, tested :white_check_mark:

**Pull request merged**
