### PR TITLE
front: fix key spread log errors in maps

### LINKED ISSUE #9134: Map trigger an error log at initialization
### What happened?

It looks like the map is triggering an error log during initialization.

### What did you expect to happen?

No error log

```ts
Warning: A props object containing a "key" prop is being spread into JSX:
  let props = {key: someKey, id: ..., type: ..., source: ..., source-layer: ..., minzoom: ..., filter: ..., paint: ..., layerOrder: ...};
  <OrderedLayer {...props} />
React keys must be passed directly to JSX without using spread:
  let props = {id: ..., type: ..., source: ..., source-layer: ..., minzoom: ..., filter: ..., paint: ..., layerOrder: ...};
  <OrderedLayer key={someKey} {...props} />
    at OSM (http://localhost:4000/src/common/Map/Layers/OSM.tsx?t=1727788541341:67:16)
    at div
    at div
    at Map3 (http://localhost:4000/node_modules/.vite/deps/chunk-ARL2SEGY.js?v=8918695d:1416:12)
    at Map (http://localhost:4000/src/modules/trainschedule/components/ManageTrainSchedule/Map.tsx?t=1727788541341:57:16)
    at div
    at div
    at div
    at StdcmConfig (http://localhost:4000/src/applications/stdcmV2/components/StdcmConfig.tsx?t=1727788541341:31:24)
    at div
    at div
    at StdcmViewV2 (http://localhost:4000/src/applications/stdcmV2/views/StdcmViewV2.tsx?t=1727788541341:26:67)
    at RenderedRoute (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=3a374b56:4092:5)
    at Routes (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=3a374b56:4531:5)
    at HomeStdcm
    at RenderedRoute (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=3a374b56:4092:5)
    at Outlet (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=3a374b56:4467:26)
    at ModalProvider (http://localhost:4000/src/common/BootstrapSNCF/ModalSNCF/ModalProvider.tsx:75:37)
    at OsrdContextLayout (http://localhost:4000/src/common/osrdContext.tsx:104:37)
    at RenderedRoute (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=3a374b56:4092:5)
    at RenderErrorBoundary (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=3a374b56:4052:5)
    at DataRoutes (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=3a374b56:5211:5)
    at Router (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=3a374b56:4474:15)
    at RouterProvider (http://localhost:4000/node_modules/.vite/deps/react-router-dom.js?v=3a374b56:5026:5)
    at Suspense
    at App (http://localhost:4000/src/main/app.jsx?t=1727788541341:194:22)
    at PersistGate2 (http://localhost:4000/node_modules/.vite/deps/redux-persist_integration_react.js?v=ead47bd6:86:5)
    at Provider (http://localhost:4000/node_modules/.vite/deps/chunk-OPHDM7MH.js?v=8918695d:1097:3)
    at Container
```

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM.
2. Open the developer tools.
3. You will see the error log."

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

1355d03

### PR DESCRIPTION
**Pull request by RomainValls**
closes #9134

### CODE REVIEW

**Comment by clarani** [comment]
I think this warning was fixed by this [PR](https://github.com/OpenRailAssociation/osrd/pull/9273), you could still reproduce it on dev ?

**Comment by emersion** [comment]
Note, the fix linked above hasn't been released yet.

**Comment by SharglutDev** [comment]
Tested on dev (local), don't have any remaining error like that anymore.

**Comment by RomainValls** [comment]
Has been fixed already.

**Pull request closed without merging**
