### PR TITLE
front: fix when no curves are selected in rolling stock curve component

### LINKED ISSUE #5365: Un-ticking every speed-effort curve collapses the rolling stock component
### What happened?

This :

https://github.com/osrd-project/osrd/assets/86296016/7533ffee-b738-47b0-8cc4-2dce3a01142e

### What did you expect to happen?

The graph should become empty but the user must be able to tick the curves display again.

### How can we reproduce it (as minimally and precisely as possible)?

1. Reproduce the video

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

a6b9322e

### PR DESCRIPTION
**Pull request by Wadjetz**
close #5365

### CODE REVIEW

**Review by SharglutDev — APPROVED** [review]
Lgtm, tested in local and works as expected :)

If you can just remove the uppercase from your commit and it's perfect.

**Comment by flomonster** [comment]
Shouldn't we see the graph (with scales) without curves when nothing is selected?

**Comment by SharglutDev** [comment]
I asked that myself but as it's the same behavior in the rolling stock editor, thought it was intended.

But seems a bit weird yes.

**Comment by Wadjetz** [comment]
This is how the graph lib works, without the data it cannot build the axes or you have to find a way to give it axes by default (I can look at the lib doc to find that)

**Comment by Wadjetz** [comment]
In the meantime i can keep the axes names

**Comment by axrolld** [comment]
I agree thath the scales should remain if that's possible.

Also, be careful when sharing screenshots of rolling stocks on github, the data are not public 😬 We're not supposed to identify a rolling stock with its corresponding data.

**Review by clarani — APPROVED** [review]
LGTM, tested :heavy_check_mark:

**Pull request merged**
