### PR TITLE
front: split the ScenarioView into 2 components

### LINKED ISSUE #8867: front: small refacto of the ScenarioView
### Description and goal

Small refacto of the ScenarioView, to simplify the code and the logic

### Acceptance criteria

The code is easier to understand and maintain

### PR DESCRIPTION
**Pull request by clarani**
closes #8867

See commits
- create a new component ScenarioDescription which contains all the info of the Scenario
- create a new component ScenarioBody which contains the main content of the ScenarioView once we have a timetable, a scenario and an infra

### CODE REVIEW

**Comment by achrafmohye** [comment]
🚀 Amazing PR! Thanks for the great work! 🙌
 Don't know if necessary at this part of the refacto or at all 
Adding memoization to: `trainScheduleSummaries` and `projectedTrains` (avoid re-sorting),
`trainScheduleUsedForProjection` (optimize lookups),
`upsertTrainSchedules` (prevent re-renders).
Should boost performance?!

**Comment by clarani** [comment]
Thanks for your review @achrafmohye, I think every thing is already memoized with useMemo or useCallback in useScenarioData, do you think I can do something else ?

**Comment by clarani** [comment]
I added some memoization (for removeTrains and toggleMicroMacroButton)

**Review by Uriel-Sautron — APPROVED** [review]
Excellent work thank you.
Tested

**Review by achrafmohye — APPROVED** [review]
LGTM and tested, thanks for the great work 👍

**Review by Math-R — APPROVED** [review]
Lgtm nice work ! Much cleaner like this :)

**Pull request merged**
