### PR TITLE
front: remove relative imports

### LINKED ISSUE #6027: front: remove "import ../../../../../../../../../../../../../../../../../../somefile" (relative import paths)
Use absolute path everywhere in the app. Unless motivated exception. Thx!

### PR DESCRIPTION
**Pull request by clarani**
closes #6027

### CODE REVIEW

**Review by Wadjetz — APPROVED** [review]

**Review by SharglutDev — COMMENTED** [review]
Should we keep the relative imports for the components importing other editor parts ?

**Comment by clarani** [comment]
Well spotted, I think I forgot some :)

**Review by RomainValls — APPROVED** [review]

**Comment by kmer2016** [comment]
Some files still have a relative

- [ ] front/src/applications/editor/tools/rangeEdition/types.ts, line 4
- [ ] front/src/common/Pathfinding/__tests__/Pathfinding.spec.ts, line 1
- [ ] front/src/modules/rollingStock/components/RollingStockEditor/__tests__/RollingStockEditorForm.spec.ts, line 5
- [ ] front/src/modules/rollingStock/helpers/__tests__/utils.spec.ts, lines 2 and 3
- [ ] front/src/modules/simulationResult/components/ChartHelpers/__tests__/ChartHelpers.spec.ts, lines 8, 10, 11
- [ ] front/src/modules/simulationResult/components/SimulationResultsMap/__tests__/helpers.spec.ts, line 3
- [ ] front/src/modules/trainschedule/components/ManageTrainSchedule/Allowances/__tests__/allowances.spec.ts, line 5 and 6
- [ ] front/src/reducers/osrdconf/__tests__/helpers.spec.ts line 1
- [ ] front/src/reducers/osrdconf/stdcmConf/stdcmConfReducers.spec.ts, line 10


I don't know if we have to use absolute path in open-api-config file too. (front/src/config/openapi-editoast-config.ts and front/src/config/openapi-gateway-config.ts)

**Review by SharglutDev — APPROVED** [review]

**Review by kmer2016 — APPROVED** [review]
Well done !

**Pull request merged**
