### PR TITLE
front: highlight the stdcm train in the space time chart

### LINKED ISSUE #8519: front: the stdcm train is not hightlighted
### What happened?

The stdcm train is not highlighted on the Space Time Chart

### What did you expect to happen?

It should be highlighted

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a stdcm train in the debug interface
2. The stdcm train is not highlighted in the space time chart

### On which environments the bug occurs?

_No response_

### On which browser the bug occurs?

_No response_

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by clarani**
closes #8519

image

### CODE REVIEW

**Review by bloussou — APPROVED** [review]
🎉

**Review by eckter — APPROVED** [review]
Tested, nice

**Review by Uriel-Sautron — APPROVED** [review]
Tested, LGTM

**Review by kmer2016 — APPROVED** [review]
LGTM

**Review by achrafmohye — COMMENTED** [review]
LGTM

**Pull request merged**
