### PR TITLE
Fix missing rolling stock when editing an invalid train schedule

### LINKED ISSUE #8413: Missing rolling stock when editing an invalid train schedule
### What happened?

When editing an invalid train schedule the rolling stock selector is empty.

image

### What did you expect to happen?

We should see the rolling stock used by the train schedule.

> [!NOTE]
> If the rolling_stock_name doesn't match any rolling stock then we can keep it empty.

### How can we reproduce it (as minimally and precisely as possible)?

1. Import [train_schedules.json](https://github.com/user-attachments/files/16562088/train_schedules.json)
2. Edit it

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

db3ce245158b055f93e30563c784195151c5e2de

### PR DESCRIPTION
**Pull request by achrafmohye**
Closes #8413

### CODE REVIEW

**Review by theocrsb — APPROVED** [review]
LGTM and tested !

**Comment by kmer2016** [comment]
The first time I open the edition form, the field is not empty. But when I close and open again, the train field is empty again.

**Comment by kmer2016** [comment]
When I change the rs, and comeback to the edition form, I loose the changed one and the form reset with the previrous train

**Review by kmer2016 — APPROVED** [review]
LGTM and tested

**Pull request merged**
